version: 1
directions_count: 16
joint_margin_degrees: 0.25
gaits:
  ripple:
  - angle_degrees: 0.0
    max_step_length_m: 0.103149
  - angle_degrees: 22.5
    max_step_length_m: 0.06958
  - angle_degrees: 45.0
    max_step_length_m: 0.062927
  - angle_degrees: 67.5
    max_step_length_m: 0.069458
  - angle_degrees: 90.0
    max_step_length_m: 0.062622
  - angle_degrees: 112.5
    max_step_length_m: 0.069458
  - angle_degrees: 135.0
    max_step_length_m: 0.065308
  - angle_degrees: 157.5
    max_step_length_m: 0.072876
  - angle_degrees: 180.0
    max_step_length_m: 0.1073
  - angle_degrees: 202.5
    max_step_length_m: 0.072876
  - angle_degrees: 225.0
    max_step_length_m: 0.065308
  - angle_degrees: 247.5
    max_step_length_m: 0.069458
  - angle_degrees: 270.0
    max_step_length_m: 0.062622
  - angle_degrees: 292.5
    max_step_length_m: 0.069458
  - angle_degrees: 315.0
    max_step_length_m: 0.062927
  - angle_degrees: 337.5
    max_step_length_m: 0.06958
  wave:
  - angle_degrees: 0.0
    max_step_length_m: 0.14032
  - angle_degrees: 22.5
    max_step_length_m: 0.080017
  - angle_degrees: 45.0
    max_step_length_m: 0.071045
  - angle_degrees: 67.5
    max_step_length_m: 0.069458
  - angle_degrees: 90.0
    max_step_length_m: 0.062622
  - angle_degrees: 112.5
    max_step_length_m: 0.069458
  - angle_degrees: 135.0
    max_step_length_m: 0.067261
  - angle_degrees: 157.5
    max_step_length_m: 0.074097
  - angle_degrees: 180.0
    max_step_length_m: 0.1073
  - angle_degrees: 202.5
    max_step_length_m: 0.074097
  - angle_degrees: 225.0
    max_step_length_m: 0.067261
  - angle_degrees: 247.5
    max_step_length_m: 0.069458
  - angle_degrees: 270.0
    max_step_length_m: 0.062622
  - angle_degrees: 292.5
    max_step_length_m: 0.069458
  - angle_degrees: 315.0
    max_step_length_m: 0.071045
  - angle_degrees: 337.5
    max_step_length_m: 0.080017
  tripod:
  - angle_degrees: 0.0
    max_step_length_m: 0.107056
  - angle_degrees: 22.5
    max_step_length_m: 0.069519
  - angle_degrees: 45.0
    max_step_length_m: 0.062622
  - angle_degrees: 67.5
    max_step_length_m: 0.069458
  - angle_degrees: 90.0
    max_step_length_m: 0.062622
  - angle_degrees: 112.5
    max_step_length_m: 0.069458
  - angle_degrees: 135.0
    max_step_length_m: 0.062622
  - angle_degrees: 157.5
    max_step_length_m: 0.069519
  - angle_degrees: 180.0
    max_step_length_m: 0.107056
  - angle_degrees: 202.5
    max_step_length_m: 0.069519
  - angle_degrees: 225.0
    max_step_length_m: 0.062622
  - angle_degrees: 247.5
    max_step_length_m: 0.069458
  - angle_degrees: 270.0
    max_step_length_m: 0.062622
  - angle_degrees: 292.5
    max_step_length_m: 0.069458
  - angle_degrees: 315.0
    max_step_length_m: 0.062622
  - angle_degrees: 337.5
    max_step_length_m: 0.069519
