controller_manager:
  ros__parameters:
    update_rate: 1000  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
      update_rate: 100  # Hz

    battery_state_broadcaster:
      type: battery_state_broadcaster/BatteryStateBroadcaster
      update_rate: 10  # Hz

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController
      update_rate: 100  # Hz

joint_trajectory_controller:
  ros__parameters:
    joints:
      - dr_qp/left_front_coxa
      - dr_qp/left_front_femur
      - dr_qp/left_front_tibia

      - dr_qp/right_front_coxa
      - dr_qp/right_front_femur
      - dr_qp/right_front_tibia


      - dr_qp/left_middle_coxa
      - dr_qp/left_middle_femur
      - dr_qp/left_middle_tibia

      - dr_qp/right_middle_coxa
      - dr_qp/right_middle_femur
      - dr_qp/right_middle_tibia


      - dr_qp/left_back_coxa
      - dr_qp/left_back_femur
      - dr_qp/left_back_tibia

      - dr_qp/right_back_coxa
      - dr_qp/right_back_femur
      - dr_qp/right_back_tibia

    command_interfaces:
      - position
      - effort

    state_interfaces:
      - position
      - velocity

    action_monitor_rate: 20.0 # Defaults to 20

    allow_partial_joints_goal: true # Defaults to false
    interpolate_from_desired_state: true
    allow_integration_in_goal_trajectories: true
    constraints:
      stopped_velocity_tolerance: 0.01 # Defaults to 0.01
      goal_time: 0.0 # Defaults to 0.0 (start immediately)



# https://docs.ros.org/en/iron/p/battery_state_broadcaster/
battery_state_broadcaster:
  ros__parameters:
    sensor_name: "battery_state"
    # https://github.com/ros2/common_interfaces/blob/jazzy/sensor_msgs/msg/BatteryState.msg
    power_supply_technology: 3 # POWER_SUPPLY_TECHNOLOGY_LIPO
