repos:
- repo: https://github.com/kynan/nbstripout
  rev: 0.8.1
  hooks:
    - id: nbstripout
  # Enable in separate PR
  #- repo: https://github.com/pre-commit/pre-commit-hooks
  #  rev: v2.3.0
  #  hooks:
  #   - id: check-yaml
  #   - id: end-of-file-fixer
  #   - id: trailing-whitespace

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.11.2
  hooks:
    - id: ruff-format
    - id: ruff # lint
      args: [ --fix ]
    - id: ruff # isort
      args: [ --fix, --select, I ]


- repo: https://github.com/mwouts/jupytext
  rev: v1.17.0
  hooks:
  - id: jupytext
    args: [--sync, --pipe-fmt, py:percent, --pipe, 'ruff format {}', --pipe, 'ruff check --fix --ignore E402,F811 {}', --pipe, 'ruff check --fix --select I {}']
    additional_dependencies:
    - ruff==v0.11.2

- repo: https://github.com/gitleaks/gitleaks
  rev: v8.24.3
  hooks:
    - id: gitleaks

- repo: https://github.com/rhysd/actionlint
  rev: v1.7.7
  hooks:
    - id: actionlint
