# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the OS, Python version, and other tools you might need
build:
  os: ubuntu-24.04
  tools:
    nodejs: "20" # keep in sync with environment.yml
    python: "3.12" # keep in sync with environment.yml
  apt_packages:
    - ffmpeg
  commands:
    - pip install uv
    - uv sync --group docs
    - uv run sphinx-build -b html docs/source $READTHEDOCS_OUTPUT/html
