[tool.ruff]
# Same as Black.
line-length = 100
indent-width = 4

# Assume Python 3.12
target-version = "py312"

[tool.ruff.lint]
# Enable:
# - pycodestyle (E, W)
# - Pyflakes (F)
# - flake8-blind-except (BLE)
# - pydocstyle (D)
# - isort (I)
# - pycodestyle warnings (W)
select = ["E", "W", "F", "BLE", "D", "I", "D213"]

# Never enforce `E501` (line length violations) - handled by formatter
# Ignore D212 in favor of D213
ignore = ["E501", "D212"]

[tool.ruff.format]
# Use single quotes for strings
quote-style = "single"

# Indent with 4 spaces
indent-style = "space"

[tool.ruff.lint.pep8-naming]
# Allow Pydantic's `cls` parameter to be lowercase
classmethod-decorators = [
    "classmethod",
    "pydantic.validator",
    "pydantic.root_validator",
]

[tool.ruff.lint.per-file-ignores]
# Ignore unused imports in __init__.py files
"__init__.py" = ["F401"]

[tool.ruff.lint.pydocstyle]
convention = "google"
