line-length = 100
indent-width = 4

# Assume Python 3.12
target-version = "py312"

[format]
# Use single quotes for strings
quote-style = "single"

# Indent with 4 spaces
indent-style = "space"

[lint]
# Enable:
# - pycodestyle (E, W)
# - Pyflakes (F)
# - flake8-blind-except (BLE)
# - pydocstyle (D)
# - pycodestyle warnings (W)
# - D200: One-line docstring should fit on one line with quotes
# - D213: Multi-line docstring summary should start at the second line
select = ["E", "W", "F", "BLE", "D200", "D213"]

# Never enforce `E501` (line length violations) - handled by formatter
# Ignore D212 in favor of D213
ignore = ["E501", "D212"]

[lint.isort]
# Import sorting configuration
force-single-line = false
force-sort-within-sections = true # sort all imports within section no matter the style
combine-as-imports = true
known-third-party = ["rclpy", "sensor_msgs", "tf2_ros", "pytest", "drqp_brain"]
case-sensitive = false
order-by-type = false # ignore type, use alphabetical order


[lint.pep8-naming]
# Allow Pydantic's `cls` parameter to be lowercase
classmethod-decorators = [
    "classmethod",
    "pydantic.validator",
    "pydantic.root_validator",
]

[lint.per-file-ignores]
# Ignore unused imports in __init__.py files
"__init__.py" = ["F401"]

[lint.pydocstyle]
convention = "google"
