#!/usr/bin/env bash
set -e

script_dir="$(dirname $0)"
source "$script_dir/__utils.sh"

if isCI; then
  set -x
fi

# Basic prerequisites
sudo apt update \
  && sudo apt-get install -y -q --no-install-recommends \
  software-properties-common \
  wget \
  fish \
  curl \
  gnupg2 \
  lsb-release \
  ca-certificates \
  apt-utils
# Enable community-maintained free and open-source software (universe).
sudo add-apt-repository universe -y

# check for UTF-8
function is_utf8_locale()
{
  local loc=$(locale)
  if [[ $loc =~ LANG=.*\.UTF-8 ]] || [[ $loc =~ LC_ALL=.*\.UTF-8 ]]; then
    echo 'yes'
  else
    echo 'no'
  fi
}

if [[ $(is_utf8_locale) == 'no' ]]; then
  sudo apt-get install -y -q --no-install-recommends locales
  sudo locale-gen en_US en_US.UTF-8
  sudo update-locale LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8
  export LANG=en_US.UTF-8
fi
test $(is_utf8_locale) == 'yes' || (echo "Failed to set en_US.UTF-8 locale" && exit 1)

# Add ros signing keys
if [[ ! (-f /etc/apt/sources.list.d/ros2-latest.list || -f /etc/apt/sources.list.d/ros2.list) ]]; then
  sudo curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key  -o /usr/share/keyrings/ros-archive-keyring.gpg
  echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu $(source /etc/os-release && echo $UBUNTU_CODENAME) main" | sudo tee /etc/apt/sources.list.d/ros2.list > /dev/null
fi

# CMake
test -f /usr/share/doc/kitware-archive-keyring/copyright || wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | gpg --dearmor - | sudo tee /usr/share/keyrings/kitware-archive-keyring.gpg >/dev/null
echo 'deb [signed-by=/usr/share/keyrings/kitware-archive-keyring.gpg] https://apt.kitware.com/ubuntu/ jammy main' | sudo tee /etc/apt/sources.list.d/kitware.list >/dev/null

sudo apt update
test -f /usr/share/doc/kitware-archive-keyring/copyright || sudo rm /usr/share/keyrings/kitware-archive-keyring.gpg
sudo apt-get install -y -q --no-install-recommends kitware-archive-keyring

sudo apt upgrade -y -q

sudo apt-get install -y -q --no-install-recommends \
  build-essential \
  cmake \
  ninja-build \
  git \
  git-lfs \
  libbullet-dev \
  lcov \
  python3-colcon-common-extensions \
  python3-colcon-coveragepy-result \
  python3-colcon-lcov-result \
  python3-colcon-mixin \
  python3-coverage \
  python3-flake8 \
  python3-flake8-blind-except \
  python3-flake8-class-newline \
  python3-flake8-deprecated \
  python3-mypy \
  python3-pip \
  python3-pytest \
  python3-pytest-cov \
  python3-pytest-mock \
  python3-pytest-repeat \
  python3-pytest-rerunfailures \
  python3-pytest-runner \
  python3-pytest-timeout \
  python3-rosdep \
  python3-setuptools \
  python3-vcstool \
  ros-dev-tools \
  libasio-dev \
  libtinyxml2-dev \
  libcunit1-dev

# install colcon mixins under ROOT
colcon mixin remove default || true
colcon mixin add default https://raw.githubusercontent.com/colcon/colcon-mixin-repository/b8436aa16c0bdbc01081b12caa253cbf16e0fb82/index.yaml
colcon mixin update default

sudo rm -f /etc/ros/rosdep/sources.list.d/*
sudo rosdep init

if [[ $SOURCE_INSTALL == 1 ]]; then
  "$script_dir/ros-2-src-build.sh"
else
  sudo apt-get install -y -q --no-install-recommends ros-$ROS_DISTRO-desktop
fi

# Install known dependencies generated by ./scripts/ros/ros-dep-gen.sh
"$script_dir/install_dependencies.sh"

# Install Node.js and NPM for drqp_hexapod_js and local GHA via nektos/act to work
curl -sL https://deb.nodesource.com/setup_20.x -o $script_dir/nodesource_setup.sh
sudo bash $script_dir/nodesource_setup.sh
sudo apt-get -y remove nodejs npm # remove old versions if any
# The NodeSource nodejs package contains both the node binary and npm, so you don’t need to install npm separately.
sudo apt-get install -y -q --no-install-recommends nodejs
sudo npm install -g yarn

# Install latest Clang
# If installation fails with output containing Skipping acquire of configured file 'main/binary-i386/Packages'
# Add `[arch=amd64]` to llvm apt list
# code /etc/apt/sources.list.d/archive_uri-http_apt_llvm_org_noble_-noble.list
# More details are in https://stackoverflow.com/a/79155511/888545
CLANG_VERSION=19
curl -sSL https://apt.llvm.org/llvm.sh -o "$script_dir/llvm.sh"
chmod +x "$script_dir/llvm.sh"
sudo "$script_dir/llvm.sh" $CLANG_VERSION all

echo '##################################################'
echo '#'
echo '#'  Add /usr/lib/llvm-19/bin to \$PATH
echo '#'
echo '#'  for fish \(in ~/.config/fish/config.fish\):
echo '#'  'set -gx PATH /usr/lib/llvm-19/bin $PATH'
echo '#'
echo '#'
echo '#'  for bash \(in ~/.bashrc\):
echo '#'  'export PATH="/usr/lib/llvm-19/bin:$PATH"'
echo '#'
echo '#'
echo '#'  for dockerfile
echo '#'  'ENV PATH="/usr/lib/llvm-19/bin:$PATH"'
echo '#'
echo '##################################################'
