---
- name: Install basic prerequisites
  ansible.builtin.apt:
    name:
      - software-properties-common
      - wget
      - fish
      - curl
      - gnupg2
      - lsb-release
      - ca-certificates
      - apt-utils
    state: present
    update_cache: true
    install_recommends: false

- name: Enable community-maintained free and open-source software (universe repository)
  ansible.builtin.apt_repository:
    state: present
    repo: "{{ item }}"
  loop:
    - "deb [arch={{ ansible_architecture }}] http://ports.ubuntu.com/ubuntu-ports {{ ansible_distribution_release }} universe"
    - "deb [arch={{ ansible_architecture }}] http://ports.ubuntu.com/ubuntu-ports {{ ansible_distribution_release }}-updates universe"
    - "deb [arch={{ ansible_architecture }}] http://ports.ubuntu.com/ubuntu-ports {{ ansible_distribution_release }}-security universe"
