---
# ROS 2 repository setup using new apt-source approach
- name: Get latest ros-apt-source release version
  ansible.builtin.uri:
    url: https://api.github.com/repos/ros-infrastructure/ros-apt-source/releases/latest
    return_content: true
  register: ros_repo_release_info

- name: Extract version from release info
  ansible.builtin.set_fact:
    ros_repo_apt_source_version: "{{ ros_repo_release_info.json.tag_name }}"

- name: Download ros2-apt-source package
  ansible.builtin.get_url:
    url: "https://github.com/ros-infrastructure/ros-apt-source/releases/download/{{ ros_repo_apt_source_version }}/ros2-apt-source_{{ ros_repo_apt_source_version
      }}.{{ system_dist }}_all.deb"
    dest: /tmp/ros2-apt-source.deb
    mode: "0644"

- name: Install ros2-apt-source package
  ansible.builtin.apt:
    deb: /tmp/ros2-apt-source.deb
    state: present

- name: Clean up downloaded package
  ansible.builtin.file:
    path: /tmp/ros2-apt-source.deb
    state: absent
