---
# ROS repository setup
- name: Check if ROS 2 repository is already configured
  ansible.builtin.stat:
    path: /etc/apt/sources.list.d/ros2-latest.list
  register: ros2_repo

- name: Download ROS 2 signing key
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/ros/rosdistro/master/ros.key
    dest: /usr/share/keyrings/ros2-latest-archive-keyring.gpg
    mode: "0644"
  when: not ros2_repo.stat.exists

- name: Get Ubuntu codename
  ansible.builtin.command: lsb_release -cs
  register: ubuntu_codename
  changed_when: false
  when: not ros2_repo.stat.exists

- name: Get system architecture
  ansible.builtin.command: dpkg --print-architecture
  register: system_arch
  changed_when: false
  when: not ros2_repo.stat.exists

- name: Add ROS 2 repository
  ansible.builtin.apt_repository:
    repo: >-
      deb [arch={{ system_arch.stdout }} signed-by=/usr/share/keyrings/ros2-latest-archive-keyring.gpg]
      http://packages.ros.org/ros2/ubuntu {{ ubuntu_codename.stdout }} main
    state: present
    filename: ros2
  when: not ros2_repo.stat.exists
