version: '3.4'
services:
  ser2net:
    # image: danrue/ser2net:3.5
    build: 
      context: .
      dockerfile: ser2net.dockerfile
    volumes:
      - ./ser2net.conf:/etc/ser2net.conf
    restart:
      unless-stopped
    # Ports and devices, same as in ser2net.conf
    ports:
      - 2022:2022
    devices:
      - /dev/ttySC0

  ros-base:
    image: dr-qp/ros-base
    build:
      context: ..
      dockerfile: docker/ros-base.dockerfile

  ros-desktop:
    image: dr-qp/ros-desktop
    build:
      context: ..
      dockerfile: docker/ros-desktop.dockerfile
    depends_on:
      - ros-base
