version: '3.4'
services:
  ser2net:
    # image: danrue/ser2net:3.5
    build: 
      context: .
      dockerfile: ser2net.dockerfile
    volumes:
      - ./ser2net.yml:/etc/ser2net.yml

    # Ports and devices, same as in ser2net.yml
    ports:
      - 2022:2022
    devices:
      - /dev/ttyAMA0

