- ros_topic_name: 'clock'
  gz_topic_name: '/clock'
  ros_type_name: 'rosgraph_msgs/msg/Clock'
  gz_type_name: 'gz.msgs.Clock'
  direction: GZ_TO_ROS # BIDIRECTIONAL or ROS_TO_GZ

# Robot odometry for velocity tracking
- ros_topic_name: '/model/drqp/odometry'
  gz_topic_name: '/model/drqp/odometry'
  ros_type_name: 'nav_msgs/msg/Odometry'
  gz_type_name: 'gz.msgs.Odometry'
  direction: GZ_TO_ROS

# 9-DOF IMU data from simulated BNO055 sensor
- ros_topic_name: '/imu/data'
  gz_topic_name: '/model/drqp/imu/data'
  ros_type_name: 'sensor_msgs/msg/Imu'
  gz_type_name: 'gz.msgs.IMU'
  direction: GZ_TO_ROS
