---
# Clang installation
- name: Create temporary directory for downloads
  ansible.builtin.tempfile:
    state: directory
  register: temp_dir
  become: false

- name: Download LLVM installation script
  ansible.builtin.get_url:
    url: https://apt.llvm.org/llvm.sh
    dest: "{{ temp_dir.path }}/llvm.sh"
    mode: "0755"
  become: false

- name: Run LLVM installation script
  ansible.builtin.command: bash "{{ temp_dir.path }}/llvm.sh" {{ clang_version }} all
  register: llvm_install
  changed_when: llvm_install.stdout is search('Installing')
- name: Install libstdc++ development package
  ansible.builtin.apt:
    name: libstdc++-14-dev
    state: present
    install_recommends: false

- name: Display Clang path information
  ansible.builtin.debug:
    msg:
      - "##################################################"
      - "#"
      - "#  Add /usr/lib/llvm-{{ clang_version }}/bin to $PATH"
      - "#"
      - "#  for fish (in ~/.config/fish/config.fish):"
      - "#  set -gx PATH /usr/lib/llvm-{{ clang_version }}/bin $PATH"
      - "#"
      - "#"
      - "#  for bash (in ~/.bashrc):"
      - "#  export PATH=\"/usr/lib/llvm-{{ clang_version }}/bin:$PATH\""
      - "#"
      - "#"
      - "#  for dockerfile"
      - "#  ENV PATH=\"/usr/lib/llvm-{{ clang_version }}/bin:$PATH\""
      - "#"
      - "##################################################"

- name: Clean up temporary directory
  ansible.builtin.file:
    path: "{{ temp_dir.path }}"
    state: absent
  become: false
