name: Docker metadata action
description: Extract metadata (tags, labels) for docker image
inputs:
  images:
    description: 'Image names to pass to metadata-action'
    default: ''
  arch:
    description: 'Architecture to use as suffix'
    required: true
    default: ${{ runner.arch }}
  github-token:
    description: 'GitHub token'
    required: true
    default: ${{ github.token }}
outputs:
  tags:
    description: "Docker tags for the images"
    value: ${{ steps.meta.outputs.tags }}
  labels:
    description: "Docker labels for the images"
    value: ${{ steps.meta.outputs.labels }}
runs:
  using: "composite"
  steps:
    - uses: docker/metadata-action@v5
      id: meta
      with:
        github-token: ${{ inputs.github-token }}
        images: ${{ inputs.images }}
        tags: |
          type=ref,event=branch,suffix=-${{ inputs.arch }}
          type=ref,event=pr,suffix=-${{ inputs.arch }}
          type=semver,pattern={{version}},suffix=-${{ inputs.arch }}
          type=semver,pattern={{major}}.{{minor}},suffix=-${{ inputs.arch }}
          type=edge,branch=main,suffix=-${{ inputs.arch }}
