---
- name: Normalize architecture
  ansible.builtin.set_fact:
    system_arch: "{{ 'arm64' if ansible_architecture == 'aarch64' else ansible_architecture }}"
    system_dist: "{{ ansible_distribution | lower }}"
