services:
  devcontainer:
    image: ghcr.io/dr-qp/jazzy-ros-desktop:edge
    privileged: true
    network_mode: host
    ipc: host
    pid: host
    # Uncomment to allow shared memory based DDS communication
    # user: "1001:1001", # Change to match primary user on the host
    volumes:
      # Volumes for git worktree
      - ${GIT_REPO}:${GIT_REPO}:rw
      - ${LOCAL_WORKSPACE_FOLDER}:${LOCAL_WORKSPACE_FOLDER}:rw

      # Local ROS overlay workspace
      - ${LOCAL_WORKSPACE_FOLDER}:/opt/ros/overlay_ws/:rw
    command: ["sleep", "infinity"]
