---
- name: Docker POC Setup
  hosts: virtual_bots
  tasks:
    - name: Pull the base image
      community.docker.docker_image:
        name: ubuntu:24.04
        source: pull
    - name: Create and start containers
      community.docker.docker_container:
        name: virtual-bot-{{ item }}
        image: ubuntu:24.04
        state: started
      with_sequence:
        count: 3
