---
- name: Bring up virtual bots
  hosts: local
  vars:
    container_image: "ghcr.io/dr-qp/jazzy-ros-deploy:edge"
  tasks:
    - name: Pull the base image
      community.docker.docker_image:
        name: "{{ container_image }}"
        source: pull

    - name: Create and start containers
      community.docker.docker_container:
        name: virtual-bot-{{ item }}
        image: "{{ container_image }}"
        state: started
        detach: true
        command: sleep infinity
      with_sequence: start=1 end=3
