---
- name: Setup startup service to bring ROS nodes up in docker container
  hosts: robots
  become: true
  vars:
    container_image: "ghcr.io/dr-qp/jazzy-ros-deploy:edge"
    container_name: "drqp-ros-deploy-edge"
    service_name: "drqp-ros-deploy-docker"
  tasks:
    - name: Pull Docker image from GitHub Container Registry
      community.docker.docker_image:
        name: "{{ container_image }}"
        source: pull

    - name: Create systemd service to run container on boot
      ansible.builtin.copy:
        mode: "0644"
        dest: "/etc/systemd/system/{{ service_name }}.service"
        content: |
          [Unit]
          Description=Dr.QP ROS container
          After=docker.service
          Requires=docker.service

          [Service]
          Restart=always
          # Force network mode for DDS network https://robotics.stackexchange.com/a/114955/38643
          # Environment=FASTDDS_BUILTIN_TRANSPORTS=UDPv4
          ExecStart=/usr/bin/docker run --pull=always \
            --network host \
            --ipc host \
            --pid host \
            --device /dev/ttySC0 \
            --device /dev/input/event0 \
            --device /dev/input/event1 \
            --device /dev/input/event2 \
            --device /dev/input/event3 \
            --device /dev/input/event4 \
            --device /dev/input/event5 \
            --device /dev/input/event6 \
            --device /dev/input/event7 \
            --rm \
            --name {{ container_name }} \
             {{ container_image }}
          ExecStop=/usr/bin/docker stop {{ container_name }}

          [Install]
          WantedBy=multi-user.target

    - name: Enable and start autorun service
      ansible.builtin.systemd_service:
        daemon-reload: true
        name: "{{ service_name }}"
        enabled: true
        state: reloaded
