- name: Setup startup service to bring ROS nodes up in docker container
  hosts: robots
  become: true
  tasks:
  - name: Install Docker dependencies
    apt:
      name:
        - apt-transport-https
        - ca-certificates
        - curl
        - software-properties-common
      state: present
      update_cache: yes

  - name: Add Docker GPG key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present
      keyring: /etc/apt/keyrings/docker.asc


  - name: Add Docker repository
    apt_repository:
      repo: deb [arch=arm64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu noble stable
      state: present
      filename: docker
      update_cache: yes

  - name: Install Docker Engine
    apt:
      name:
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - docker-buildx-plugin
        - docker-compose-plugin
        - fuse-overlayfs
      state: latest
      update_cache: yes

  - name: Configure Docker daemon
    copy:
      dest: /etc/docker/daemon.json
      content: |
        {
          "log-driver": "json-file",
          "log-opts": {
            "max-size": "10m",
            "max-file": "3"
          }
        }

  - name: Restart Docker service to apply config changes
    service:
      name: docker.service
      state: restarted
      enabled: true
      daemon_reload: true

  - name: Ensure containerd service is running
    service:
      name: containerd.service
      state: started
      enabled: true

  - name: Create docker group
    group:
      name: docker
      state: present

  - name: Add user to docker group
    user:
      name: "{{ ansible_user }}"
      groups: docker
      append: yes
