- name: Setup startup service to bring ROS nodes up in docker container
  hosts: robots
  become: true
  vars:
    container_image: "ghcr.io/dr-qp/jazzy-ros-deploy:edge"
    container_name: "drqp-ros-deploy-edge"
    service_name: "drqp-ros-deploy-docker"
  tasks:
  - name: Pull Docker image from GitHub Container Registry
    community.docker.docker_image:
      name: "{{ container_image }}"
      source: pull

  - name: Create systemd service to run container on boot
    become: true
    copy:
      dest: "/etc/systemd/system/{{ service_name }}.service"
      content: |
        [Unit]
        Description=Dr.QP ROS container
        After=docker.service
        Requires=docker.service

        [Service]
        Restart=always
        ExecStart=/usr/bin/docker run --pull=always --network host --device /dev/ttySC0 --rm --name {{ container_name }} {{ container_image }}
        ExecStop=/usr/bin/docker stop {{ container_name }}

        [Install]
        WantedBy=multi-user.target

  - name: Enable and start autorun service
    systemd_service:
      daemon-reload: true
      name: "{{ service_name }}"
      enabled: yes
      state: reloaded
