---
# ROS repository setup
- name: Check if ROS 2 repository is already configured
  ansible.builtin.stat:
    path: /etc/apt/sources.list.d/ros2.list
  register: ros2_repo

- name: Download ROS 2 signing key
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/ros/rosdistro/master/ros.key
    dest: /usr/share/keyrings/ros-archive-keyring.gpg
    mode: "0644"
  when: not ros2_repo.stat.exists

- name: Add ROS 2 repository
  ansible.builtin.shell: |
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu $(. /etc/os-release && echo $UBUNTU_CODENAME) main" | tee /etc/apt/sources.list.d/ros2.list > /dev/null
  args:
    creates: /etc/apt/sources.list.d/ros2.list
  when: not ros2_repo.stat.exists
