---
- name: Install Docker on robots
  hosts: robots
  become: true
  gather_facts: true
  roles:
    - { role: extra_facts, tags: ["extra_facts"] }
    - { role: install_docker, tags: ["install_docker"] }
