---
# Colcon mixin setup
- name: Temp dir for colcon logs
  ansible.builtin.tempfile:
    state: directory
  register: temp_dir
  become: false

- name: Setup colcon mixin
  ansible.builtin.import_tasks: colcon_mixin.yml

- name: Setup colcon metadata
  ansible.builtin.import_tasks: colcon_metadata.yml
