name: Log debug stats
description: Print GitHub API debug statistics for the current job

inputs:
  github-token:
    description: GitHub token used to authenticate API requests
    required: true

runs:
  using: composite
  steps:
    - name: Print REST API rate limits
      uses: actions/github-script@f28e40c7f34bde8b3046d885e986cb6290c5673b # v7
      with:
        github-token: ${{ inputs.github-token }}
        script: |
          const { data } = await github.request('GET /rate_limit');
          core.info(JSON.stringify(data, null, 2));
