version: '3.4'
services:
  ros-base:
    image: ghcr.io/dr-qp/ros-base
    build:
      context: ..
      dockerfile: ./ros-base.dockerfile

  ros-desktop:
    image: ghcr.io/dr-qp/ros-desktop
    build:
      context: ..
      dockerfile: ./ros-desktop.dockerfile
    depends_on:
      - ros-base
