name: Build ubuntu images

on:
  schedule:
    - cron: 0 12 */7 * *
  push:
    paths:
      - .github/workflows/act-docker-build-image.yml
      - docker/act/**
    branches:
      - main
  pull_request:
    paths:
      - .github/workflows/act-docker-build-image.yml
      - docker/act/**
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

env:
  IMAGE_LABEL_OWNER: ${{ github.repository_owner }}
  IMAGE_LABEL_REPO: ${{ github.repository }}
  SLUG: ${{ github.repository_owner }}/act-ubuntu
  DISTRO: ubuntu
  NODE: 20
  BUILD_REF: ${{ github.sha }}
  SKIP_TEST: false
  REGISTRY: ghcr.io
  REGISTRY_USERNAME: ${{ github.actor }} # for nektos/act, use your own username via --actor option


  LATEST_TAG: 24.04

defaults:
  run:
    shell: sh

jobs:
  build:
    name: Build
    if: "!contains(github.event.pull_request.body, '[skip build]')"
    runs-on: ${{ matrix.arch == 'amd64' && 'ubuntu-24.04' || 'ubuntu-24.04-arm' }}
    timeout-minutes: 120
    permissions:
      packages: write
    strategy:
      fail-fast: true
      max-parallel: 4
      matrix:
        arch:
          - amd64
          - arm64
        TAG:
          - 24.04
          - 22.04
    steps:
      - uses: actions/checkout@v4
      - name: Force SLUG to lowercase
        uses: actions/github-script@v6
        with:
          github-token: n/a
          script: |
            core.exportVariable('SLUG', process.env.SLUG.toLowerCase());

      - name: Build act docker image
        id: build
        uses: ./.github/actions/docker/build-push-action
        with:
          context: docker/act
          image: ${{ env.REGISTRY }}/${{ env.SLUG }}
          arch: ${{ matrix.arch }}
          registry: ${{ env.REGISTRY }}
          registry-username: ${{ env.REGISTRY_USERNAME }}
          registry-token: ${{ secrets.GITHUB_TOKEN }}
          build-args: |
            DISTRO_VERSION=${{ matrix.TAG }}

  merge:
    name: Merge multiarch act image
    runs-on: ubuntu-24.04-arm
    permissions:
      packages: write
    needs: build
    timeout-minutes: 35
    outputs:
      image: ${{ steps.merge.outputs.image }}
    steps:
      - name: Force SLUG to lowercase
        uses: actions/github-script@v6
        with:
          github-token: n/a
          script: |
            core.exportVariable('SLUG', process.env.SLUG.toLowerCase());

      - uses: actions/checkout@v4
      - name: Merge and push act docker image
        id: merge
        uses: ./.github/actions/docker/multiarch-merge
        with:
          image: ${{ env.REGISTRY }}/${{ env.SLUG }}
          registry: ${{ env.REGISTRY }}
          registry-username: ${{ env.REGISTRY_USERNAME }}
          registry-token: ${{ secrets.GITHUB_TOKEN }}
  test:
    name: Test act image
    runs-on: ${{ matrix.arch == 'amd64' && 'ubuntu-24.04' || 'ubuntu-24.04-arm' }}
    needs: merge
    timeout-minutes: 120
    permissions:
      packages: read
    strategy:
      fail-fast: true
      max-parallel: 4
      matrix:
        arch:
          - amd64
          - arm64
        TAG:
          - 24.04
          - 22.04
    steps:
      - uses: actions/setup-go@v5
        if: ${{ !env.SKIP_TEST }}
        with:
          go-version: '^1.16'

      - name: Checkout nektos/act repo
        uses: actions/checkout@v4
        if: ${{ !env.SKIP_TEST }}
        with:
          repository: nektos/act
          path: act

      - shell: bash
        if: ${{ !env.SKIP_TEST }}
        env:
          ACT_TEST_IMAGE: ${{ needs.merge.outputs.image }}
        run: |
          cd act/
          go test ./...
