name: CI/CD

on:
  release:
    types:
      - published
  push:
    branches:
      - 'main'
    tags:
      - 'v*'
  merge_group:
    types:
      - checks_requested
  pull_request:
    branches:
      - 'main'
      - 'v*'

env:
  ROS_DISTRO: humble
  CC: clang
  CXX: clang++
  REGISTRY: ghcr.io
  REGISTRY_USERNAME: ${{ github.actor }} # for nektos/act, use your own username via --actor option

jobs:
  build-dev-image:
    name: Development image
    timeout-minutes: 35
    outputs:
      image_arm64: ${{ contains(matrix.arch, 'arm64') && steps.build.outputs.image || '' }}
      image_amd64: ${{ contains(matrix.arch, 'amd64') && steps.build.outputs.image || '' }}
    permissions:
      contents: read
      packages: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - runner: ubuntu-24.04-arm
            arch: arm64
          - runner: ubuntu-24.04
            arch: amd64
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v4

      - name: Build development docker image
        id: build
        uses: ./.github/actions/docker/build-push-action
        with:
          context: scripts
          file: scripts/ros-desktop.dockerfile
          image: ${{ env.REGISTRY }}/dr-qp/ros-desktop
          arch: ${{ matrix.arch }}
          registry: ${{ env.REGISTRY }}
          registry-username: ${{ env.REGISTRY_USERNAME }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

  ros-ci:
    name: Build and test ROS2 workspace
    timeout-minutes: 35
    strategy:
      fail-fast: false
      matrix:
        include:
          - runner: ubuntu-24.04-arm
            arch: arm64
          - runner: ubuntu-24.04
            arch: amd64
    runs-on: ${{ matrix.runner }}
    needs: [build-dev-image]
    container:
      image: ${{ matrix.arch == 'arm64' && needs.build-dev-image.outputs.image_arm64 || needs.build-dev-image.outputs.image_amd64 }}

      options: --user rosdev # Mandatory! Sets user:group matching the one of the runner, allowing access to mounted paths

      # Only needed for nektos/act runs
      # credentials:
      #   username: ${{ env.REGISTRY_USERNAME }}
      #   password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: ros-tooling/action-ros-ci@v0.3
        id: action_ros_ci_step
        env:
          GCOV_COMMAND: "${{ github.workspace }}/scripts/gcov"
        with:
          target-ros2-distro: ${{ env.ROS_DISTRO }}
          colcon-defaults: |
            {
              "build": {
                "mixin": ["coverage-gcc", "coverage-pytest"]
              },
              "test": {
                "mixin": ["coverage-pytest"]
              }
            }


      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        if: env.ACT == ''
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ros_ws/lcov/total_coverage.info,ros_ws/coveragepy/.coverage
          disable_search: true
          flags: unittests-${{ matrix.arch }}
          name: codecov-umbrella

      - uses: actions/upload-artifact@v4
        # upload the logs even when the build fails
        if: env.ACT == '' && always()
        with:
          name: colcon-logs-${{ matrix.arch }}
          path: ${{ steps.action_ros_ci_step.outputs.ros-workspace-directory-name }}/log

  build-deploy-image:
    name: Deployment image
    timeout-minutes: 35
    strategy:
      fail-fast: false
      matrix:
        include:
          - runner: ubuntu-24.04-arm
            arch: arm64
          - runner: ubuntu-24.04
            arch: amd64
    runs-on: ${{ matrix.runner }}
    needs: [build-dev-image, ros-ci]
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Build deployment docker image
        uses: ./.github/actions/docker/build-push-action
        with:
          context: scripts/deploy
          file: scripts/deploy/ros-deploy.dockerfile
          image: ${{ env.REGISTRY }}/dr-qp/ros-deploy
          arch: ${{ matrix.arch }}
          registry: ${{ env.REGISTRY }}
          registry-username: ${{ env.REGISTRY_USERNAME }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          build-args: |
            ROS_DISTRO=${{ env.ROS_DISTRO }}
            GIT_SHA=${{ github.event.pull_request && github.event.pull_request.head.sha || github.sha }}
            BUILD_IMAGE=${{ matrix.arch == 'arm64' && needs.build-dev-image.outputs.image_arm64 || needs.build-dev-image.outputs.image_amd64 }}

  merge-all:
    name: CI/CD finished
    runs-on: ubuntu-24.04
    needs: [build-dev-image, ros-ci, build-deploy-image]
    steps:
      - run: echo "All jobs finished successfully"
