name: ci

on:
  release:
    types:
      - published
  push:
    branches:
      - 'main'
    tags:
      - 'v*'
  pull_request:
    branches:
      - 'main'
      - 'v*'

env:
  ROS_DISTRO: humble
  CC: clang
  CXX: clang++
  REGISTRY: ghcr.io
  REGISTRY_USERNAME: ${{ github.actor == 'nektos/act' && 'anton-matosov' || github.actor }}
  # CACHE_FROM: ${{ github.actor == 'nektos/act' && 'type=local,src=./docker-cache' || 'type=gha' }}
  # CACHE_TO: ${{ github.actor == 'nektos/act' && 'type=local,dest=./docker-cache' || 'type=gha,mode=max' }}
  CACHE_FROM: 'type=gha'
  CACHE_TO: 'type=gha,mode=max'

jobs:
  build-image:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.meta.outputs.tags }}
    permissions:
      contents: read
      packages: write
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

        # Add support for more platforms with QEMU (optional)
        # https://github.com/docker/setup-qemu-action
      # - name: Set up QEMU
      #   uses: docker/setup-qemu-action@v3
      #   with:
      #     platforms: arm64

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.REGISTRY_USERNAME }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          images: ${{ env.REGISTRY }}/dr-qp/ros-desktop
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}

      - uses: actions/checkout@v4 # Checkout the repository to allow work with nektos/act on non pushed commits
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: scripts
          file: scripts/ros-desktop.dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: ${{ env.CACHE_FROM }}
          cache-to: ${{ env.CACHE_TO }}

  ros-ci:
    runs-on: ubuntu-latest
    needs: [build-image]
    container:
      image: ${{ needs.build-image.outputs.image }}

      # Only needed for nektos/act runs
      # credentials:
      #   username: ${{ env.REGISTRY_USERNAME }}
      #   password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: ros-tooling/action-ros-ci@v0.3
        id: action_ros_ci_step
        env:
          GCOV_COMMAND: "${{ github.workspace }}/scripts/gcov"
        with:
          target-ros2-distro: ${{ env.ROS_DISTRO }}
          colcon-defaults: |
            {
              "build": {
                "mixin": ["coverage-gcc", "coverage-pytest"]
              },
              "test": {
                "mixin": ["coverage-pytest"]
              }
            }
          # pin the repository in the workflow to a specific commit to avoid
          # changes in colcon-mixin-repository from breaking your tests.
          colcon-mixin-repository: https://raw.githubusercontent.com/colcon/colcon-mixin-repository/b8436aa16c0bdbc01081b12caa253cbf16e0fb82/index.yaml


      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ros_ws/lcov/total_coverage.info,ros_ws/coveragepy/.coverage
          disable_search: true
          flags: unittests
          name: codecov-umbrella

      - uses: actions/upload-artifact@v4
        # upload the logs even when the build fails
        if: always()
        with:
          name: colcon-logs
          path: ${{ steps.action_ros_ci_step.outputs.ros-workspace-directory-name }}/log

  dev-container-ci:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - name: Log in to the Container registry
          uses: docker/login-action@v3
          with:
            registry: ${{ env.REGISTRY }}
            username: ${{ env.REGISTRY_USERNAME }}
            password: ${{ secrets.GITHUB_TOKEN }}

        - name: Extract metadata (tags, labels) for Docker
          id: meta
          uses: docker/metadata-action@v5
          with:
            tags: |
              type=ref,event=branch
              type=ref,event=pr
              type=semver,pattern={{version}}
              type=semver,pattern={{major}}.{{minor}}

        - name: Build and test dev container image
          uses: devcontainers/ci@v0.3
          with:
            imageName: ${{ env.REGISTRY }}/dr-qp/humble-ros-devcontainer
            cacheFrom: ${{ env.REGISTRY }}/dr-qp/humble-ros-devcontainer
            push: always # only if runCmd succeeds
            configFile: .devcontainer/local/devcontainer.json
            imageTag: ${{ steps.meta.outputs.tags }}
            runCmd: |
              sudo apt update
              rosdep update
              ./scripts/ros/ros-dep.sh
              colcon build
              colcon test
