name: ci

on:
  release:
    types:
      - published
  push:
    branches:
      - 'develop'
    tags:
      - 'v*'
  pull_request:
    branches:
      - 'develop'
      - 'v*'

env:
  ROS_DISTRO: humble
  # CC: clang # TODO: uncomment this line when clang is available in the image
  # CXX: clang++
  REGISTRY: ghcr.io

jobs:
  build-image:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.meta.outputs.tags }}
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          images:
            ${{ env.REGISTRY }}/dr-qp/ros-desktop

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: scripts
          file: scripts/ros-desktop.dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  ros-ci:
    runs-on: ubuntu-latest
    needs: [build-image]
    container:
      # image: ros:humble-ros-base # base image is good for testing deployment packages. keep it here as an example
      # Use desktop image as there is gazebo which is a desktop package that has tons of dependencies
      # image: osrf/ros:humble-desktop

      image: ${{ needs.build-image.outputs.image }}
      options: --user 1001:121 # Mandatory 1.0. Sets user:group matching the one of the runner, allowing access to mounted paths
    steps:
      - run: sudo apt-get update && sudo apt-get install -y python3-colcon-coveragepy-result
      - uses: actions/checkout@v2
      - uses: ros-tooling/action-ros-ci@v0.3
        with:
          target-ros2-distro: humble
