name: ci

on:
  release:
    types: 
      - published
  push:
    branches:
      - 'develop'
    tags:
      - 'v*'
  pull_request:
    branches:
      - 'develop'
      - 'v*'

jobs:
  test-cpp:
    runs-on: ubuntu-latest
    container:
      image: osrf/ros:humble-ros-core
    steps:
      - uses: actions/checkout@v2
      - uses: ros-tooling/action-ros-ci@v0.3
      with:
        target-ros2-distro: humble
