name: ci

on:
  push:
  release:
    types: [published]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }} # Dr-QP/Dr.QP

jobs:
  build-and-push-docker-image:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - run: env | sort
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: 
            ghcr.io/dr-qp/ros-base:latest

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: docker/ros-base.dockerfile
          push: ${{ github.event.release.tag_name != '' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - uses: addnab/docker-run-action@v3
        with:
          image: ghcr.io/dr-qp/ros-base:latest
          run: ros2 pkg list

  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: Install ROS2 conda environment
  #       uses: mamba-org/provision-with-micromamba@main
  #       with:
  #         environment-file: scripts/ros/ros_env.yml