name: ci

on:
  release:
    types: 
      - published
  push:
    branches:
      - 'develop'
    tags:
      - 'v*'
  pull_request:
    branches:
      - 'develop'
      - 'v*'

jobs:
  ros-ci:
    runs-on: ubuntu-latest
    container:
      image: ros:humble-ros-base
    steps:
      - uses: actions/checkout@v2
      - uses: ros-tooling/action-ros-ci@v0.3
        with:
          target-ros2-distro: humble
