name: ci

on:
  push:
  release:
    types: [published]

env:
  REGISTRY: ghcr.io

jobs:
  build-and-push-docker-image:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - run: env | sort
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: 
            ${{ env.REGISTRY }}/dr-qp/ros-base

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: docker/ros-base.dockerfile
          push: ${{ github.event.release.tag_name != '' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - run: docker run --rm ${{ steps.meta.outputs.tags }} ros2 pkg list
        shell: bash

  test:
    needs: [build-and-push-docker-image]
    runs-on: ubuntu-latest
    container:
      image: ${{ env.REGISTRY }}/dr-qp/ros-base
    steps:
      - uses: actions/checkout@v3
      - shell: bash
        run: |
          mkdir build
          cd build
          cmake -G Ninja ..
          ninja
