name: ci

on:
  release:
    types: 
      - published
  push:
    branches:
      - 'develop'
    tags:
      - 'v*'
  pull_request:
    branches:
      - 'develop'
      - 'v*'

jobs:
  ros-ci:
    runs-on: ubuntu-latest
    container:
      # image: ros:humble-ros-base # base image is good for testing deployment packages. keep it here as an example
      # Use desktop image as there is gazebo which is a desktop package that has tons of dependencies
      image: ros:humble-ros-desktop
    steps:
      - uses: actions/checkout@v2
      - uses: ros-tooling/action-ros-ci@v0.3
        with:
          target-ros2-distro: humble
