name: CI/CD

on:
  release:
    types:
      - published
  push:
    paths:
      - .github/workflows/ci.yml
      - .github/actions/**
      - docker/ros/**
      - packages/**
      - scripts/**
      - .clang-format
      - codecov.yml
    branches:
      - main
    tags:
      - v*
  pull_request:
    paths:
      - .github/workflows/ci.yml
      - .github/actions/**
      - docker/ros/**
      - packages/**
      - scripts/**
      - .clang-format
      - codecov.yml
    branches:
      - main
      - v*
  merge_group:
    types:
      - checks_requested

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

env:
  ROS_DISTRO: jazzy
  CC: clang
  CXX: clang++
  REGISTRY: ghcr.io
  REGISTRY_USERNAME: ${{ github.actor }} # for nektos/act, use your own username via --actor option

jobs:
  build-dev-image:
    name: Development image
    timeout-minutes: 35
    permissions:
      packages: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - runner: ${{ vars.AMD_ONLY == '1' && 'ubuntu-24.04' || 'ubuntu-24.04-arm' }}
            arch: ${{ vars.AMD_ONLY == '1' && 'amd64' || 'arm64' }}
          - runner: ${{ vars.ARM_ONLY == '1' && 'ubuntu-24.04-arm' || 'ubuntu-24.04' }}
            arch: ${{ vars.ARM_ONLY == '1' && 'arm64' || 'amd64' }}
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v4

      - name: Build development docker image
        id: build
        uses: ./.github/actions/docker/build-push-action
        with:
          context: scripts
          file: scripts/ros-desktop.dockerfile
          image: ${{ env.REGISTRY }}/dr-qp/${{ env.ROS_DISTRO }}-ros-desktop
          arch: ${{ matrix.arch }}
          registry: ${{ env.REGISTRY }}
          registry-username: ${{ env.REGISTRY_USERNAME }}
          registry-token: ${{ secrets.GITHUB_TOKEN }}
          build-args: |
            ROS_DISTRO=${{ env.ROS_DISTRO }}

  merge-dev-image:
    name: Merge development image
    runs-on: ubuntu-24.04-arm
    permissions:
      packages: write
    needs:
      - build-dev-image
    timeout-minutes: 35
    outputs:
      image: ${{ steps.merge.outputs.image }}
    steps:
      - uses: actions/checkout@v4
      - name: Merge and push development docker image
        id: merge
        uses: ./.github/actions/docker/multiarch-merge
        with:
          image: ${{ env.REGISTRY }}/dr-qp/${{ env.ROS_DISTRO }}-ros-desktop
          registry: ${{ env.REGISTRY }}
          registry-username: ${{ env.REGISTRY_USERNAME }}
          registry-token: ${{ secrets.GITHUB_TOKEN }}

  ros-ci:
    name: Build and test ROS2 workspace
    needs: [merge-dev-image]
    timeout-minutes: 35
    strategy:
      fail-fast: false
      matrix:
        include:
          - runner: ${{ vars.AMD_ONLY == '1' && 'ubuntu-24.04' || 'ubuntu-24.04-arm' }}
            arch: ${{ vars.AMD_ONLY == '1' && 'amd64' || 'arm64' }}
          - runner: ${{ vars.ARM_ONLY == '1' && 'ubuntu-24.04-arm' || 'ubuntu-24.04' }}
            arch: ${{ vars.ARM_ONLY == '1' && 'arm64' || 'amd64' }}
    runs-on: ${{ matrix.runner }}
    permissions:
      packages: read
    container:
      image: ${{ needs.merge-dev-image.outputs.image }}
      options: --user rosdev # Mandatory! Sets user:group matching the one of the runner, allowing access to mounted paths
    steps:
      - uses: actions/checkout@v4
      - uses: ros-tooling/action-ros-ci@v0.3
        env:
          GCOV_COMMAND: "${{ github.workspace }}/scripts/gcov"
        with:
          target-ros2-distro: ${{ env.ROS_DISTRO }}
          no-symlink-install: true
          colcon-defaults: |
            {
              "build": {
                "mixin": ["coverage-gcc", "coverage-pytest"]
              },
              "test": {
                "mixin": ["coverage-pytest"]
              }
            }

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        if: env.ACT == ''
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ros_ws/lcov/total_coverage.info,ros_ws/coveragepy/.coverage
          disable_search: true
          flags: unittests-${{ matrix.arch }}
          name: codecov-umbrella

      - uses: actions/upload-artifact@v4
        # upload the logs even when the build fails
        if: always()
        with:
          name: colcon-logs-${{ matrix.arch }}
          path: ros_ws/log
          retention-days: 100

  build-deploy-image:
    name: Deployment image
    needs: [merge-dev-image, ros-ci]
    timeout-minutes: 35
    strategy:
      fail-fast: false
      matrix:
        include:
          - runner: ${{ vars.AMD_ONLY == '1' && 'ubuntu-24.04' || 'ubuntu-24.04-arm' }}
            arch: ${{ vars.AMD_ONLY == '1' && 'amd64' || 'arm64' }}
          - runner: ${{ vars.ARM_ONLY == '1' && 'ubuntu-24.04-arm' || 'ubuntu-24.04' }}
            arch: ${{ vars.ARM_ONLY == '1' && 'arm64' || 'amd64' }}
    runs-on: ${{ matrix.runner }}
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Build deployment docker image
        uses: ./.github/actions/docker/build-push-action
        with:
          context: scripts/deploy
          file: scripts/deploy/ros-deploy.dockerfile
          image: ${{ env.REGISTRY }}/dr-qp/ros-deploy
          arch: ${{ matrix.arch }}
          registry: ${{ env.REGISTRY }}
          registry-username: ${{ env.REGISTRY_USERNAME }}
          registry-token: ${{ secrets.GITHUB_TOKEN }}
          build-args: |
            ROS_DISTRO=${{ env.ROS_DISTRO }}
            GIT_SHA=${{ github.event.pull_request && github.event.pull_request.head.sha || github.sha }}
            BUILD_IMAGE=${{ needs.merge-dev-image.outputs.image }}

  merge-deploy-image:
    name: Merge deployment image
    runs-on: ubuntu-24.04-arm
    permissions:
      packages: write
    needs:
      - build-deploy-image
    timeout-minutes: 35
    outputs:
      image: ${{ steps.merge.outputs.image }}
    steps:
      - uses: actions/checkout@v4
      - name: Merge and push deployment docker image
        id: merge
        uses: ./.github/actions/docker/multiarch-merge
        with:
          image: ${{ env.REGISTRY }}/dr-qp/ros-deploy
          registry: ${{ env.REGISTRY }}
          registry-username: ${{ env.REGISTRY_USERNAME }}
          registry-token: ${{ secrets.GITHUB_TOKEN }}
  merge-all:
    name: CI/CD finished
    needs: [merge-dev-image, ros-ci, merge-deploy-image]
    runs-on: ubuntu-24.04-arm
    permissions: {}
    steps:
      - run: echo "All jobs finished successfully"
